### ISSUE TITLE
[BUG] Can't find stronghold

### ISSUE THREAD

**Issue by gardenappl** [DaFuqs/StarrySky#32]
Eye of Ender does not work (right-click plays an animation but the item is not consumed), and `/locate stronghold` says "An unexpected error occurred trying to execute that command"

Console shows this stack trace:
```
Error executing task on Server
java.lang.NullPointerException: Cannot invoke "de.dafuqs.starrysky.advancements.SpheroidAdvancementIdentifier.equals(Object)" because the return value of "de.dafuqs.starrysky.spheroid.spheroids.Spheroid.getSpheroidAdvancementIdentifier()" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.12)
	at de.dafuqs.starrysky.Support.getClosestSpheroid3x3(Support.java:80)
	at de.dafuqs.starrysky.dimension.StarrySkyChunkGenerator.returnClosestStrongholdSphere(StarrySkyChunkGenerator.java:93)
	at de.dafuqs.starrysky.dimension.StarrySkyChunkGenerator.locateStructure(StarrySkyChunkGenerator.java:105)
	at net.minecraft.item.EnderEyeItem.use(EnderEyeItem:83)
	at net.minecraft.item.ItemStack.use(ItemStack:252)
	at net.minecraft.server.network.ServerPlayerInteractionManager.interactItem(ServerPlayerInteractionManager:282)
	at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractItem(ServerPlayNetworkHandler:1093)
	at net.minecraft.network.packet.c2s.play.PlayerInteractItemC2SPacket.apply(PlayerInteractItemC2SPacket:25)
	at net.minecraft.network.packet.c2s.play.PlayerInteractItemC2SPacket.apply(PlayerInteractItemC2SPacket:7)
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21)
	at net.minecraft.server.ServerTask.run(ServerTask:18)
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:151)
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23)
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:780)
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:162)
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:125)
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:762)
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:756)
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:134)
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:741)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:688)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:270)
	at java.lang.Thread.run(Thread.java:833)
```

**Comment by gardenappl** [comment]
```
Loading 162 mods:
	- advanced_runtime_resource_pack 0.5.4 via enhancedblockentities
	- advancementinfo 1.18-fabric0.43.1-1.3
	- antighost 1.18-fabric0.43.1-1.1.4
	- architectury 3.2.60
	- autoconfig1u 3.3.1
	- bettermounthud 1.1.3
	- blue_endless_jankson 1.2.1 via kyrptconfig
	- borderlessmining 1.1.1+1.18
	- buildinggadgets 1.0.7
	- cardinal-components-base 4.0.0 via buildinggadgets
	- cardinal-components-item 4.0.0 via buildinggadgets
	- cardinal-components-level 4.0.0 via buildinggadgets
	- cardinal-components-world 4.0.0 via buildinggadgets
	- cem 0.7.0
	- cloth-api 2.0.54
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-client-events-v0 2.0.54 via cloth-api
	- cloth-common-events-v1 2.0.54 via cloth-api
	- cloth-config 6.1.48
	- cloth-datagen-api-v1 2.0.54 via cloth-api
	- cloth-scissors-api-v1 2.0.54 via cloth-api
	- cloth-utils-v1 2.0.54 via cloth-api
	- colormatic 2.4.0+mc.1.18
	- com_fasterxml_jackson_dataformat_jackson-dataformat-yaml 2.13.0 via essential_commands
	- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
	- completeconfig 1.3.3
	- continuity 1.0.3+1.18
	- croptosis 1.3.0
	- crowdin-translate 1.4+1.18 via antighost
	- cullleaves 2.3.2
	- customportalapi 0.0.1-beta46v2-1.18 via starry_sky
	- dcch 1.0
	- diggusmaximus 1.5.2-1.18
	- dynamicfps 2.0.6
	- ec-core 1.0.1-mc1.18.1 via essential_commands
	- enhancedblockentities 0.5+1.18
	- entityculling 1.3.3
	- essential_commands 0.19.0-mc1.18.1
	- expandedstorage 7.3.6
	- explorerscompass 1.18.1-2.0.2-fabric
	- extragenerators 1.1.1-BETA+1.18
	- fabric 0.45.0+1.18
	- fabric-api-base 0.4.1+b4f4f6cd65 via fabric
	- fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric
	- fabric-biome-api-v1 6.0.1+ded849a965 via fabric
	- fabric-blockrenderlayer-v1 1.1.9+3ac43d9565 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d9565 via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.18+d154e2c665 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.7+43d2957165 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a65 via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric
	- fabric-item-api-v1 1.3.0+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric
	- fabric-key-binding-api-v1 1.0.8+c8aba2f365 via fabric
	- fabric-keybindings-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-language-kotlin 1.7.1+kotlin.1.6.10
	- fabric-lifecycle-events-v1 1.4.10+c15ca33565 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric
	- fabric-mining-levels-v0 0.1.7+b4f4f6cd65 via fabric
	- fabric-models-v0 0.3.3+3ac43d9565 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d9565 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.0+3b82842e65 via fabric
	- fabric-object-builders-v0 0.7.8+3ac43d9565 via fabric
	- fabric-particles-v1 0.2.9+526dc1ac65 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via essential_commands
	- fabric-registry-sync-v0 0.8.6+533be9ba65 via fabric
	- fabric-renderer-api-v1 0.4.9+3ac43d9565 via fabric
	- fabric-renderer-indigo 0.4.12+3ac43d9565 via fabric
	- fabric-renderer-registries-v1 3.2.7+b4f4f6cd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric
	- fabric-rendering-v0 1.1.9+b4f4f6cd65 via fabric
	- fabric-rendering-v1 1.10.3+6b21378a65 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d9514 via borderlessmining
	- fabric-screen-api-v1 1.0.7+3ac43d9565 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric
	- fabric-structure-api-v1 2.0.8+295197a765 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d9565 via fabric
	- fabric-textures-v0 1.0.9+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.4+7de09f5565 via fabric
	- fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric
	- fabricloader 0.12.12
	- fabrilousupdater 2.5+1.18.1
	- fabrishot 1.6.0
	- fake-player-api 0.3.0 via indrev
	- fastopenlinksandfolders 1.0.0
	- ferritecore 4.0.0
	- fiber 0.23.0-2 via patchouli
	- globalspawn 1.5.0-1.18.1
	- hookshot 23.0
	- indium 1.0.2-alpha1+mc1.18
	- indrev 1.13.2-BETA
	- iris 1.1.3
	- iron-jetpacks 0.4.3
	- itemmodelfix 1.0.3+1.18
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- kibe 1.9.4-BETA+1.18
	- kyrptconfig 1.2.4-1.18 via diggusmaximus
	- languagereload 1.2
	- lazydfu 0.1.2
	- libblockattributes_core 0.10.0 via indrev
	- libblockattributes_fluids 0.10.0 via indrev
	- libblockattributes_items 0.10.0 via indrev
	- libgui 5.0.0+1.18 via indrev
	- libninepatch 1.1.0 via libgui
	- lightoverlay 6.0.4
	- lithium 0.7.6
	- magna 1.7.0-1.18-pre1 via indrev
	- midnightlib 0.2.9 via cullleaves
	- minecraft 1.18.1
	- mm 2.1 via slight-gui-modifications
	- modmenu 3.0.1
	- morechathistory 1.1.0
	- ninjaphenix_container_lib 1.2.8
	- no-telemetry 1.3.0
	- nofade 1.18-2.0.1
	- notenoughcrashes 4.1.3+1.18
	- omega-config 1.0.8 via magna
	- org_anarres_jcpp 1.4.14 via iris
	- org_codehaus_groovy_groovy 3.0.8 via slight-gui-modifications
	- org_codehaus_groovy_groovy-jsr223 3.0.8 via slight-gui-modifications
	- org_jetbrains_kotlin_kotlin-reflect 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- org_slf4j_slf4j-api 1.7.12 via iris
	- patchouli 1.18-60-FABRIC via indrev
	- placeholder-api 1.1.3+1.17.1 via essential_commands
	- playerabilitylib 1.4.0 via kibe
	- reborncore 5.1.0-beta.4 via techreborn
	- reeses-sodium-options 1.2.3
	- resourcemelons 2.2.3
	- resourcemelonstechreborn 1.0.0
	- roughlyenoughitems 7.1.357
	- roughlyenoughresources 2.3.0
	- slight-gui-modifications 2.0.2
	- smoothboot 1.18-1.7.0
	- sodium 0.4.0-alpha5+build.9
	- sodium-extra 0.3.7
	- starlight 1.0.0+fabric.d0a3220
	- starry_sky 1.5.0-1.18.1
	- step-height-entity-attribute 1.0.0 via indrev
	- team_reborn_energy 2.1.0 via iron-jetpacks
	- techreborn 5.1.0-beta.4
	- tooltipfix 1.0.4-1.18
	- wi_zoom 1.3-MC1.18.1
	- yigd 1.2.10
	- yosbr 0.1.1
```
Sorry for the long dump

**Comment by gardenappl** [comment]
```
16:08:30.616
starry_sky
Render thread
[StarrySkies] Block techreborn:copper_ore does not exist! It will be treated as air
16:08:30.623
starry_sky
Render thread
[StarrySkies] Block indrev:copper_ore does not exist! It will be treated as air
16:08:30.664
starry_sky
Render thread
[StarrySkies] CoreSpheroidType: Registered a SpheroidType with null coreBlock!
```
Got some warnings while booting up

**Comment by gardenappl** [comment]
I've also been messing with configs (enabled Pride spheres) in an already existing world, maybe that messed something up, too.

**Comment by DaFuqs** [comment]
Thank you for the whole lot of logs, that will help a ton. :)
3 things:
- I will take a look at your Stronghold issue and will fix the locating / console error
- Since copper is now in vanilla Tech Reborn and IndRev removed their own coppers, rightly so. That means I can clean up some stuff on my end, too.
- Adjusting the configs while the world already was generated will give your hard chunk borders, but otherwise everything else will work just fine.

**Comment by DaFuqs** [comment]
I cant replicate your issue with the Ender Pearl at all. Are there any mods that modify advancements in your pack?

**Comment by DaFuqs** [comment]
As of 1.18.2 this logic has to be moved to structure locating instead of handling it with mixin

**Comment by DaFuqs** [comment]
Fixed
